---
apiVersion: v1
kind: Service
metadata:
  name: bggdb-svc
  namespace: bggns
  labels:
    app: bggdb
    name: bggdb-svc
spec:
  type: ClusterIP
  selector: 
    app: bgg
    name: bggdb-po
  ports:
  - port: 3306
    targetPort: 3306