---
apiVersion: v1
kind: Namespace
metadata:
  name: minio-ns
  labels:
    app: minio
    name: minio-app

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-pvc
  namespace: minio-ns
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: do-block-storage

# ---
# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: minio-cm
#   namespace: minio-ns
#   ...

---
apiVersion: v1
kind: Service
metadata:
  name: minio-hsvc
  namespace: minio-ns
  labels:
    app: minio
spec:
  clusterIP: None
  selector:
    app: minio
    name: minio-po
  ports:
  - name: data
    port: 9000
    targetPort: 9000
  - name: console
    port: 9090
    targetPort: 9090

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: minio-sts
  namespace: minio-ns
  labels:
    app: minio
spec:
  replicas: 4
  serviceName: minio-hsvc
  selector:
    matchLabels:
      app: minio
      name: minio-po
  volumeClaimTemplates:
  - metadata:
      name: data-vol
    spec:
      accessModes: [ ReadWriteOnce ]
      storageClassName: do-block-storage
      resources:
        requests:
          storage: 1Gi
  template: 
    metadata:
      labels:
        app: minio
        name: minio-po
    spec:
      securityContext:
        fsGroup: 1001
      # volumes:
      # - name: workspace-vol
      #   persistentVolumeClaim:
      #     claimName: minio-pvc
      containers:
      - name: minio-container
        image: bitnami/minio:2024.8.29
        imagePullPolicy: IfNotPresent
        envFrom:
        - configMapRef:
            name: minio-cm
        - secretRef:
            name: minio-secret
        ports:
        - name: data
          containerPort: 9000
        - name: console
          containerPort: 9090
        volumeMounts:
        - name: data-vol
          mountPath: /data
        resources:
          requests:
            cpu: 200m
            memory: 250Mi
            
---
apiVersion: v1
kind: Service
metadata:
  name: minio-svc
  namespace: minio-ns
spec:
  type: ClusterIP
  selector:
    app: minio
    name: minio-po
  ports:
  - name: data
    port: 9000
    targetPort: 9000
  - name: console
    port: 9090
    targetPort: 9090

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minio-ing
  namespace: minio-ns
spec:
  ingressClassName: nginx
  rules:
  - host: data.104.248.98.190.nip.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: minio-svc
            port:
              number: 9000
  - host: console.104.248.98.190.nip.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: minio-svc
            port:
              number: 9090